FROM python:3.11

ARG DIFY_API_KEY
ARG ENOM_RESELLER_ID
ARG ENOM_RESELLER_PASSWORD
ARG ENOM_TEST_MODE

ENV DIFY_API_KEY=${DIFY_API_KEY}
ENV ENOM_RESELLER_ID=${ENOM_RESELLER_ID}
ENV ENOM_RESELLER_PASSWORD=${ENOM_RESELLER_PASSWORD}
ENV ENOM_TEST_MODE=${ENOM_TEST_MODE}


WORKDIR /app

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8080"]
