name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: destilabs
  GCP_REGION: us-central1

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - id: "auth"
      uses: "google-github-actions/auth@v1"
      with:
        credentials_json: "${{ secrets.GCP_SA_KEY }}"

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v2'
      with:
        version: '>= 363.0.0'
        project_id: destilabs

    - name: Build and push Docker image
      run: |
        gcloud auth configure-docker us-central1-docker.pkg.dev
        docker build -t us-central1-docker.pkg.dev/destilabs/gcf-artifacts/jvg:${{ github.sha }} \
          --build-arg ENOM_RESELLER_ID=${{ secrets.ENOM_RESELLER_ID }} \
          --build-arg ENOM_RESELLER_PASSWORD=${{ secrets.ENOM_RESELLER_PASSWORD }} \
          --build-arg ENOM_TEST_MODE=True \
          .
        docker push us-central1-docker.pkg.dev/destilabs/gcf-artifacts/jvg:${{ github.sha }}

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy ${{ github.event.repository.name }} \
          --image us-central1-docker.pkg.dev/destilabs/gcf-artifacts/jvg:${{ github.sha }} \
          --platform managed \
          --region ${{ env.GCP_REGION }} \
          --allow-unauthenticated
